### ISSUE TITLE
Only able to retrieve 1500 flights

### ISSUE THREAD

**Issue by DanCollinsCloud** [JeanExtreme002/FlightRadarAPI#24] opened 2022-12-05 19:53 UTC
Hi,

I am currently testing this excellent API and I am trying to retrieve all flights.

Although when running:

flights = fr_api.get_flights()

result = len(flights)

print(result)

It is only returning 1500. Is this customizable or is this a limit of the flightradar API?

Thanks

**Comment by JeanExtreme002** [comment] 2022-12-06 00:32
Duplicate of #21

**Closed by JeanExtreme002** 2022-12-06 00:32 UTC
