### ISSUE TITLE
Discrepancies in airport departures data

### ISSUE THREAD

**Issue by daniel-yang66** [JeanExtreme002/FlightRadarAPI#66] opened 2024-04-17 07:16 UTC
Hey there Jean,
I emailed you about the issue too but I’ll post here as well. So I notice some discrepancies between your data vs Flightradar24. For example between airports A and B there could be 5 flights but your data may only show 4 flights. Another scenario is when there is a flight from A to B the flight shows up in the arrivals info for B but does not show up in departures info for A. 

Really nice API. Appreciate all the hard work

**Comment by JeanExtreme002** [comment] 2024-04-19 02:47
Hi @daniel-yang66!

I tried to reproduce the problem but it seems the same to the website. By the way, all data collected by this project come from the website, then it is supposed both of them have the same result...

Which airport did you track? Did you request the flights only once or more times? 

Maybe it an unexpected behavior of the website. I'll keep checking it further. Could you try reproducing the problem again and tell me here the airports and the radius of the area you are tracking?

Thank you in advance for the report!

**Comment by daniel-yang66** [comment] 2024-04-19 05:58
Thanks for responding Jean. Take for example SFO to PEK. There is a United flight UA888 everyday. But it fails to appear as live when I use the get airport details method. The flight may be there sometimes but it is marked as not live. Note the 2 pictures below where the discrepancy is. The flight is live in the flight radar app but not seen when I use your api to display it on my dashboard. 
![D814DC75-B45E-4B04-AAE2-DCEFC36E9248](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/09574f81-a523-4503-9718-2bec6508a7e6)
![C3477C48-805B-40B5-9852-4363654E4911](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/c8838ca3-0053-4d65-a880-56a70892b474)

**Comment by daniel-yang66** [comment] 2024-04-19 06:01
The vast majority of the time, your data is correct but it is quite random where the discrepancies occur. Like one day the sfo to pek route is fine but another example would be LAX to NRT where discrepancies occur.

**Comment by daniel-yang66** [comment] 2024-04-20 01:10
See below for 4 flights live from SFO to NRT while only one shows up on my map. They seem to be labeled as not live in your json response when I call the get airport details method and go to departures
![1DB25431-E8A1-45CA-8CB4-446887CB0825](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/ec0fd687-790f-4e13-90a8-4db904f1d5f9)
![617D592B-44C6-4A47-8AA3-C396801CD243](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/56287b4d-0660-4c0f-96fa-ae2f22ff83d1)

**Comment by JeanExtreme002** [comment] 2024-04-29 17:20
Could you share your code here?

**Comment by JeanExtreme002** [comment] 2024-04-29 19:12
I was running tests at that airport (by the way, sorry for the delay in responding, I've been really busy in the past few weeks), and I think I've understood the issue. I believe there's some confusion here. That 'live' on the website is different from the 'live' returned in the flight status in the code. It indicates that the flight hasn't started yet. As you can see in the image below, after a certain time, the status changed from False to True. The get_flights() method usually doesn't return flights that haven't started or have already ended.

![image](https://github.com/JeanExtreme002/FlightRadarAPI/assets/45553309/264a17d3-6308-4346-b9b0-44829563b3c6)

**Comment by daniel-yang66** [comment] 2024-04-29 20:51
Oh okay I see what you are saying. So the 'live' in your API indicates 'start/ no start'. How is that determined? Engines running? Aircraft ADS-B turned on? Thank you fore responding and understanding my question

**Comment by daniel-yang66** [comment] 2024-04-29 20:58
What if an aircraft is in mid-air? Shouldn't that also be labelled as 'live'? Because I notice sometimes that aircraft in mid-air are labelled as not live

**Comment by JeanExtreme002** [comment] 2024-04-29 22:00
Sorry, but I really don't know. This is just a raw information returned from flightradar24's server.

**Comment by daniel-yang66** [comment] 2024-04-29 22:19
![Screenshot (246)](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/187e4624-e254-46ed-bb65-19204adbcb87)
UAL888

**Comment by daniel-yang66** [comment] 2024-04-29 22:22
It is currently in the air on flightradar24. And regarding the definition of 'live' no worries.

My dashboard which uses your API is here: https://github.com/daniel-yang66/flight-analytics.

If you want to see my code logic, go to line 222 in the app.py file. Also, shameless plug but feel free to feature this dashboard on your api page if you feel like it

**Comment by daniel-yang66** [comment] 2024-04-29 23:07
![Uploading Screenshot (247).png…]()

**Comment by daniel-yang66** [comment] 2024-04-29 23:11
![Screenshot (247)](https://github.com/JeanExtreme002/FlightRadarAPI/assets/145522249/f224c89e-21d9-474b-b807-4c43e364b1ed)
UAL888 status currently

**Comment by JeanExtreme002** [comment] 2024-04-30 01:01
Um... I really don't know what's going on. Most likely a bug in the platform. 

Anyway, a solution to this problem would be for you to check if the flight is live by attempting to retrieve it using the `get_flights` method, passing either the airline code or its registration number. 

If it's not returned by `get_flights`, then it's certainly not live. If it is returned by the method then it's certainly live.

**Comment by daniel-yang66** [comment] 2024-04-30 02:15
Okay, sounds good. That solution will work but it will be more costly in terms of performance. Not a huge deal but left me know if you discover the root issue some time. Thanks for your effort

**Comment by JeanExtreme002** [comment] 2024-05-02 03:38
Unfortunately, no...

**Comment by JeanExtreme002** [comment] 2024-05-03 03:32
I'm closing this issue for now, because the problem of the issue is out of our control. But when the situation changes or I get any update about what is happening, I'll open it again, bringing more information.

**Closed by JeanExtreme002** 2024-05-03 03:32 UTC
Labels: Great Question
